### ISSUE TITLE
Is possible to add an image stamp using this toolkit?

### ISSUE THREAD

**Issue by RenanTashiro** [kveretennicov/dwf-toolkit#2]
Hello @kveretennicov,

Is possible to add an image stamp using this toolkit?

Regards,
Renan Tashiro

**Comment by kveretennicov** [comment]
Hi, I'm not sure. It's been a while since I used this toolkit and it was only for reading `.dwf`s.

Perhaps you can find the answer in Autodesk's docs for DFW Toolkit.

**Comment by RenanTashiro** [comment]
Hello, thank you for your quickly response. I will lookup in the doc then.

**Comment by kveretennicov** [comment]
👍
